apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example
  namespace: parodrig-gitops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thin
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
