apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
  namespace: parodrig-gitops
  finalizers: 
  - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thin
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
